#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "development"

require_relative 'lib/router'

def clean_gets
  (gets || "").chomp
end

puts IO.readlines('rec.txt')

categories_controller = CategoriesController.new()
categories_controller.add
